name: Fetch GitHub Traffic

on:
  schedule:
    - cron: '0 17 */13 * *'
  workflow_dispatch:

jobs:
  fetch-traffic:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and Sync Traffic
        uses: ./
        with:
          traffic_token: ${{ secrets.TRAFFIC_TOKEN }}

